### ISSUE TITLE
Create Ansible Task to encrypt the `users` file via the `eclipse-mosquitto` container

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#10]
## Description

A working example:

```yaml
---
- hosts: localhost
  connection: local
  tasks:
    - name: create passwd plain-text file
      copy:
       dest: "{{playbook_dir}}/users"
       content: |
        admin:testing
        test1:testing
    - name: password file for mqtt
      community.docker.docker_container:
        name: mosquitto-passgen
        image: eclipse-mosquitto:2.0.14
        state: started
        command: mosquitto_passwd -U /mosquitto/config/passwd
        volumes:
          - "{{playbook_dir}}/mosquitto.conf:/mosquitto/config/mosquitto.conf"
          - "{{playbook_dir}}/users:/mosquitto/config/passwd"

```
