### ISSUE TITLE
[node-red] Provide playbook to deploy flow

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#112]
## Description

Provide a playbook that deploys an exported flow to a remote instance. The flow needs to be explicitly provided in the CLI in order to upload the correct flow to a remote instance. Provide CLI option to start or stop (default) the flows once uploaded

**Comment by shantanoo-desai** [comment]
## Notes

- uploading nodes tarball using the Ansible `uri` module is causing corruption issues on the node-RED server see [SE Query](https://stackoverflow.com/questions/77142299/uploading-a-tarball-via-ansible-uri-module-provides-a-bad-tar-archive-error-from)

The only way that currently seems to be wrapping a `command` module with `curl`:

```yaml

    - name: upload tarballs for Node-RED
      ansible.builtin.command:
        cmd: >
          curl -s -XPOST http://localhost/nodered/nodes -H "Content-Type: multipart/form-data" \
           -H "Authorization: {{ auth_token.json.token_type }} {{ auth_token.json.access_token }}" \
           -F "tarball=@{{ komponist.deploy_dir }}/nodered/{{ item }};type=application/gzip;filename={{ item }}"
      with_items:
        - node-red-contrib-influxdb-0.6.1.tgz
```
