### ISSUE TITLE
[node-red] Generate `nodes.json` file for information on external nodes

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#114]
## Description

Generate a `nodes.json` file in the Deploy directory for Node-RED that contains the following information:

1. Module Name
2. Module Version

### Structure

```json
[
    {
        "module": "node-red-contrib-influxdb",
        "version": "0.6.1"
    },
    {
        "module": "node-red-contrib-postgresql",
        "version": "0.14.0"
    },
    {
        "module": "json-db-node-red",
        "version": "0.5.3"
    }
]
```

Use this file to install the nodes in online conditions.

**Comment by shantanoo-desai** [comment]
## Snippet

from the existing `export_nodes_nodered.yml`

```diff
diff --git a/export_nodes_nodered.yml b/export_nodes_nodered.yml
index 162d099..6270d51 100644
--- a/export_nodes_nodered.yml
+++ b/export_nodes_nodered.yml
@@ -62,6 +62,17 @@
           Accept: application/json
           Authorization: "{{ auth_token.json.token_type }} {{ auth_token.json.access_token }}"
 
+    - name: Determine External Nodes
+      ansible.builtin.set_fact:
+        external_nodes_list: "{{ external_nodes_list | default([]) + [{'module': item.module, 'version': item.version }] }}"
+      when: item.module != 'node-red'
+      loop: "{{ node_set }}"
+
+    - name: Create a nodes.json file
+      ansible.builtin.copy:
+        dest: "{{ komponist.deploy_dir }}/nodered/nodes.json"
+        content: "{{ external_nodes_list | to_nice_json }}"
+
     - name: External Nodes in Node-RED instance
       ansible.builtin.get_url:
         url: "https://registry.npmjs.org/{{ item.module }}/-/{{ item.module }}-{{ item.version }}.tgz"
```

**Comment by shantanoo-desai** [comment]
## Notes

- uploading nodes tarball using the Ansible `uri` module is causing corruption issues on the node-RED server see [SE Query](https://stackoverflow.com/questions/77142299/uploading-a-tarball-via-ansible-uri-module-provides-a-bad-tar-archive-error-from)

The only way that currently seems to be wrapping a `command` module with `curl`:

```yaml

    - name: upload tarballs for Node-RED
      ansible.builtin.command:
        cmd: >
          curl -s -XPOST http://localhost/nodered/nodes -H "Content-Type: multipart/form-data" \
           -H "Authorization: {{ auth_token.json.token_type }} {{ auth_token.json.access_token }}" \
           -F "tarball=@{{ komponist.deploy_dir }}/nodered/{{ item }};type=application/gzip;filename={{ item }}"
      with_items:
        - node-red-contrib-influxdb-0.6.1.tgz
```
