### ISSUE TITLE
[node-red] refactor bootstrapping + export nodes playbook

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#116]
## Description

Extend #111 + #110 and combine the logic of #112 where the same `bootstrap_nodered.yml` playbook can install nodes (komponist + user-specific from nodes).

1. use ansible playbook `tags` to offer user whether they want to download the tarballs offline
2. generate the `nodes.json` with all nodes (komponist + user-specific)

**Comment by shantanoo-desai** [comment]
## Notes

- uploading nodes tarball using the Ansible `uri` module is causing corruption issues on the node-RED server see [SE Query](https://stackoverflow.com/questions/77142299/uploading-a-tarball-via-ansible-uri-module-provides-a-bad-tar-archive-error-from)

The only way that currently seems to be wrapping a `command` module with `curl`:

```yaml

    - name: upload tarballs for Node-RED
      ansible.builtin.command:
        cmd: >
          curl -s -XPOST http://localhost/nodered/nodes -H "Content-Type: multipart/form-data" \
           -H "Authorization: {{ auth_token.json.token_type }} {{ auth_token.json.access_token }}" \
           -F "tarball=@{{ komponist.deploy_dir }}/nodered/{{ item }};type=application/gzip;filename={{ item }}"
      with_items:
        - node-red-contrib-influxdb-0.6.1.tgz
```
