### ISSUE TITLE
[grafana] Datasource for InfluxDBv1 does not display the database name

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#50]
## Description

There seems to a problem when connecting to InfluxDBv1 via __Save & Test__ button. For local test the `database` field in the form is empty.

Potential check for `datasources.yml` file and try adding `deleteDatasources` parameter

```yaml
# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
deleteDatasources:
```
