### ISSUE TITLE
[timescaledb] Design a configuration for TimescaleDB

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#54]
## Description

```yaml
komponist:
  configuration:
    timescaledb: 'pg15-latest'
```

There is no [default `latest` tag for timescaledb][1] so it should be a required value

[1]: https://hub.docker.com/r/timescale/timescaledb
