### ISSUE TITLE
[timescaledb] Secrets for TimescaleDB container

### ISSUE THREAD

**Issue by shantanoo-desai** [shantanoo-desai/komponist#55]
## Description

TimescaleDB uses the core Postgres configuration information. As [Postgres][1] allows to read initial secrets / credentials by File, user Docker Secrets mount logic to seed the database

```yaml
secrets:
  timescaledb:
    admin_username: <string>
    admin_password: <string>
    database: <string>
```

[1]: https://hub.docker.com/_/postgres
